FROM ubuntu:latest
RUN apt-get update -y
RUN apt-get install wget -y
RUN mkdir /opt/java8
RUN mkdir /opt/maven
RUN cd /opt/java8
RUN wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jdk-8u202-linux-x64.tar.gz"
RUN tar xvf jdk-8u202-linux-x64.tar.gz
WORKDIR /opt/java8
RUN wget https://archive.apache.org/dist/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.tar.gz
RUN tar -xvf apache-maven-3.5.3-bin.tar.gz
WORKDIR /opt/maven

ENV JAVA_HOME /opt/java8
ENV MAVEN_HOME /opt/maven
ENV PATH $PATH:$JAVA_HOME/bin:$MAVEN_HOME/bin
